Wh/22 create serverapi endpoint for editionsaddons
mcsp20-ranes-goons/frontend-capstone pull request #38
Opened 2023-05-16 23:22 UTC by Rusty12321

created serverapi endpoint for editionsaddons, and in EditionsAddons.jsx fetched data and reduced redundency.

2023-05-17 16:25 UTC, ranegray commented on client/src/components/ProductMain/ProductColumn/EditionsAddons/EditionsAddons.jsx
> +  let display = (item) => {
could do a const here, but that's just nitpicking.

2023-05-17 16:27 UTC, ranegray commented on client/src/components/ProductMain/ProductColumn/EditionsAddons/EditionsAddons.jsx
> +              <a href="https://store.epicgames.com/en-US/p/star-wars-jedi-survivor">
urls shouldn't be hardcoded. you might need to refactor the database to include urls.

2023-05-17 16:30 UTC, ranegray requested changes
Just a few little things to change and it will be way good.

2023-05-17 20:06 UTC, Rusty12321 commented
I had to set a max width on the description because once i wrapped the image in an a tag it kept changing the size of the image. Also I wrapped the image in an a tag because the image itself is a link to the page, just like the edition name.

2023-05-18 16:36 UTC, kittbg approved these changes
Looks clean.  No issues.

2023-05-18 16:39 UTC, ranegray approved these changes

2023-05-18 16:39 UTC, merged